# Generated by Django 5.2.11 on 2026-02-23 08:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('allow_mqtt', models.BooleanField(default=False)),
                ('allow_sms', models.BooleanField(default=False)),
                ('allow_whatsapp', models.BooleanField(default=False)),
                ('allow_teams', models.BooleanField(default=False)),
                ('allow_telegram', models.BooleanField(default=False)),
                ('daily_message_cap', models.IntegerField(blank=True, null=True)),
                ('devices_cap', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('billing_email', models.EmailField(max_length=254)),
                ('tech_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_uid', models.CharField(max_length=255, unique=True)),
                ('serial_number', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=100, null=True)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='licensing.customer')),
            ],
        ),
        migrations.CreateModel(
            name='GrantToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_jti', models.CharField(max_length=255, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('subscription_status', models.CharField(max_length=30)),
                ('bundle_snapshot', models.JSONField()),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_tokens', to='licensing.device')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('in_grace', 'In Grace'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=30)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('grace_days', models.IntegerField(default=15)),
                ('auto_renew', models.BooleanField(default=False)),
                ('payment_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='licensing.bundle')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='licensing.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_txn_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZAR', max_length=10)),
                ('status', models.CharField(max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='licensing.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='licensing.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('suspended', 'Suspended')], default='active', max_length=30)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('override_policy', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licensing.device')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_licenses', to='licensing.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(max_length=30)),
                ('sent_at', models.DateTimeField()),
                ('email_to', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='licensing.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='BundlePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='ZAR', max_length=10)),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='licensing.bundle')),
            ],
            options={
                'indexes': [models.Index(fields=['bundle', 'effective_from'], name='licensing_b_bundle__764d13_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['customer', 'device_uid'], name='licensing_d_custome_2ffb05_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='licensing_d_serial__cfbcad_idx'),
        ),
        migrations.AddIndex(
            model_name='granttoken',
            index=models.Index(fields=['expires_at'], name='licensing_g_expires_5ce42b_idx'),
        ),
        migrations.AddIndex(
            model_name='granttoken',
            index=models.Index(fields=['device', 'issued_at'], name='licensing_g_device__2dd95a_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicelicense',
            constraint=models.UniqueConstraint(fields=('device', 'subscription'), name='uniq_device_subscription'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionreminder',
            constraint=models.UniqueConstraint(fields=('subscription', 'reminder_type'), name='uniq_sub_reminder_type'),
        ),
    ]
