# Generated by Django 5.2.11 on 2026-02-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
