# Generated by Django 5.2.11 on 2026-03-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_subscription_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_secret_ciphertext',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='device',
            name='device_secret_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='device',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
