# Generated by Django 5.2.11 on 2026-03-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_device_device_secret_ciphertext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
