# Generated by Django 5.2.11 on 2026-03-05 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_alter_device_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='clone_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='first_seen_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='lock_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='lock_status',
            field=models.CharField(choices=[('ok', 'Ok'), ('clone_suspected', 'Clone Suspected'), ('locked', 'Locked')], default='ok', max_length=30),
        ),
        migrations.AddField(
            model_name='device',
            name='lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
