# Generated by Django 5.2.11 on 2026-03-05 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_device_clone_score_device_first_seen_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(max_length=24)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('mac_address', models.CharField(blank=True, default='', max_length=50)),
                ('nonce', models.CharField(blank=True, default='', max_length=64)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='licensing.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'timestamp'], name='licensing_v_device__e153ee_idx'), models.Index(fields=['timestamp'], name='licensing_v_timesta_68f961_idx')],
            },
        ),
    ]
