# Generated by Django 5.2.11 on 2026-03-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0006_validationlog'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='validationlog',
            constraint=models.UniqueConstraint(fields=('device', 'nonce'), name='uniq_device_nonce'),
        ),
    ]
