# Generated by Django 5.2.11 on 2026-03-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0007_validationlog_uniq_device_nonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customer',
            name='country_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='country_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
