# Generated by Django 5.2.11 on 2026-03-13 08:05

import licensing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0008_remove_customer_country_remove_customer_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='firmware_version',
        ),
        migrations.RemoveField(
            model_name='device',
            name='public_key',
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default=licensing.models.generate_customer_id, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_uid',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
