# Generated by Django 5.2.11 on 2026-03-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0009_remove_device_firmware_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_uid',
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
    ]
