# Generated by Django 5.2.11 on 2026-03-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0011_devicemodel_manufacturer_remove_device_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicemodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='devicemodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='licensing.devicemodel'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
